# 애플리케이션 기본 설정
spring:
  application:
    name: discodeit
  profiles:
    active: dev # 활성화할 프로파일 지정 (기본 로컬 개발 환경)

  # JPA 및 데이터베이스 설정
  jpa:
    hibernate:
      ddl-auto: validate # 엔티티와 DB 스키마가 일치하는지 검증만 수행
    show-sql: true       # 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true     # SQL 로그를 보기 좋게 줄바꿈 포맷팅
        highlight_sql: true  # SQL 로그에 색상 하이라이트 적용
    open-in-view: false      # OSIV 비활성화 (데이터베이스 커넥션 낭비 방지)

  # 정적 리소스(프론트엔드) 경로 설정
  web:
    resources:
      static-locations: classpath:/static/dist6/

  cache:
    type: caffeine
    cache-names:
      - channels
      - notifications
      - users
    caffeine:
      spec: >
        maximumSize=100,
        expireAfterAccess=600s,
        recordStats

#  # admin 설정 (비활성화)
#  boot:
#    admin:
#      client:
#        instance:
#          name: discodeit # 웹에 표시될 서버의 이름

# 커스텀 스토리지 설정 (파일 업로드) - s3 도입(.env 파일에 작성된 값 참조)
discodeit:
  storage:
    type: ${STORAGE_TYPE:local} # local | s3 (기본값: local)
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
  jwt:
    secret: ${JWT_SECRET_KEY:default-secret-key-must-be-long-enough-for-hs256}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION:1800000}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:1209600000}
    max-active-count: ${MAX_ACTIVE_COUNT:1}

admin:
  account:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@test.com}
    password: ${ADMIN_PASSWORD:admin1234}

# 로깅 설정
logging:
  level:
    root: info # 전체 기본 로깅 레벨

# Actuator (모니터링) 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, caches # 노출할 엔드포인트 목록
  observations:
    annotations:
      enabled: true # @Timed 어노테이션 활성화

# /actuator/info 노출 데이터 명세
info:
  app:
    name: Discodeit
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0