server:
  port: 80

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#  boot:
#    admin:
#      client:
#        url: ${SPRING_BOOT_ADMIN_CLIENT_URL} # 운영 환경에서는 유연한 주소 변경을 위해 환경 변수로 설정


logging:
  level:
    com.sprint.mission.discodeit: info