server:
  port:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234

  boot:
    admin:
      client:
        url: http://localhost:9090 # 로컬에 띄운 admin 서버 주소

logging:
  level:
    com.sprint.mission.discodeit: debug # 내가 작성한 코드만 bedug 레벨로 지정